# Config file for go-test-coverage github action.

profile: '' # set via github action
local-prefix: github.com/vladopajic/go-test-coverage/v2
threshold:
  total: 100
exclude:
  paths:
    - main\.go$