# Config file for go-test-coverage running locally.

profile: cover.profile
local-prefix: github.com/subhambhardwaj/go-test-coverage/v2
threshold:
  file: 100
  total: 98
override:
- path: badgestorer/github.go$  ## is integration test
  threshold: 64
- path: path/path.go$           ## requires windows to be tested
  threshold: 66
exclude:
  paths:
    - main\.go$