# Config file for go-test-coverage github action.

profile: cover.short.profile,cover.long.profile
local-prefix: "github.com/vladopajic/go-test-coverage/v2"
threshold:
  file: 100
  total: 100
exclude:
  paths:
    - main\.go$