# (mandatory) 
# Path to coverprofile file (output of `go test -coverprofile` command)
profile: cover.out

# (optional) 
# When specified reported file paths will not contain local prefix in the output
local-prefix: "github.com/org/project"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # (optional; default 0) 
  # The minimum coverage that each file should have
  file: 80

  # (optional; default 0) 
  # The minimum coverage that each package should have
  package: 80

  # (optional; default 0) 
  # The minimum total coverage project should have
  total: 95

# Holds regexp rules which will exclude matched files or packages from coverage statistics
exclude:
  # Exclude files or packages from coverage
  # `/` will be replaced by current OS file path separator to properly work on Windows
  paths:
    - foo\.go     # exclude all files named foo.go
    - ^pkg/bar    # exclude package pkg/bar