name: go-test-coverage
author: vladopajic
description: go-test-coverage is tool which reports issues when test coverage is below set threshold.
inputs:
  config:
    description: Path of configuration file.
    required: false
    default: "''"
    type: string
  profile:
    description: Path of coverage profile file.
    required: false
    default: "''"
    type: string
  local-prefix:
    description: When specified reported file paths will not contain local prefix in the output.
    required: false
    default: "''"
    type: string
  threshold-file:
    description: The minimum coverage that each file should have.
    required: false
    default: -1
    type: number
  threshold-package:
    description: The minimum coverage that each package should have.
    required: false
    default: -1
    type: number
  threshold-total:
    description: The minimum total coverage project should have.
    required: false
    default: -1
    type: number
  badge-file-name:
    description: When specified coverage badge will be created and saved to file with this name.
    required: false
    default: "''"
    type: string
  cdn-key:
    description: CDN key.
    required: false
    default: "''"
    type: string
  cdn-secret:
    description: CDN secret.
    required: false
    default: "''"
    type: string
  cdn-region:
    description: CDN region.
    required: false
    default: "''"
    type: string
  cdn-endpoint:
    description: CDN endpoint.
    required: false
    default: "''"
    type: string
  cdn-file-name:
    description: CDN file name.
    required: false
    default: "''"
    type: string
  cdn-bucket-name:
    description: CDN bucket name.
    required: false
    default: "''"
    type: string
  cdn-force-path-style:
    description: CDN force path style.
    required: false
    default: false
    type: boolean
outputs:
  total-coverage:
    description: Holds total coverage value.
  badge-text:
    description: Holds badge text value.
  badge-color:
    description: Holds badge color value.
runs:
  using: docker
  image: docker://ghcr.io/vladopajic/go-test-coverage:v2.7.1
  args:
    - --config=${{ inputs.config }}
    - --profile=${{ inputs.profile }}
    - --github-action-output=true
    - --local-prefix=${{ inputs.local-prefix }}
    - --threshold-file=${{ inputs.threshold-file }}
    - --threshold-package=${{ inputs.threshold-package }}
    - --threshold-total=${{ inputs.threshold-total }}
    - --badge-file-name=${{ inputs.badge-file-name }}
    - --cdn-key=${{ inputs.cdn-key }}
    - --cdn-secret=${{ inputs.cdn-secret }}
    - --cdn-region=${{ inputs.cdn-region }}
    - --cdn-endpoint=${{ inputs.cdn-endpoint }}
    - --cdn-file-name=${{ inputs.cdn-file-name }}
    - --cdn-bucket-name=${{ inputs.cdn-bucket-name }}
    - --cdn-force-path-style=${{ inputs.cdn-force-path-style }}
branding:
  icon: 'code'
  color: 'blue'