name: go-test-coverage
author: vladopajic
description: go-test-coverage is tool which reports issues when test coverage of a file or package is below set threshold.
inputs:
  config:
    description: Path of configuration file.
    required: true
outputs:
  total_coverage:
    description: Holds total coverage value.
runs:
  using: docker
  image: docker://ghcr.io/vladopajic/go-test-coverage:v1.0.0
  args:
    - -config=${{ inputs.config }}
branding:
  icon: 'code'
  color: 'blue'