name: action-test (steps)
on:
  workflow_call:
    inputs:
      variant:
        description: 'Action variant to test: docker or source'
        type: string
        required: true
      version:
        description: 'Docker image tag (docker variant) or git sha (source variant)'
        type: string
        required: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic

      - name: set action to docker image
        if: inputs.variant == 'docker'
        run: |
          yq e -i '.runs.image = "docker://ghcr.io/vladopajic/go-test-coverage:${{ inputs.version }}"' action.yml
          image=$(yq '.runs.image' action.yml)
          echo "Image: $image"

      - name: set action to source
        if: inputs.variant == 'source'
        run: cp action/source/action.yml action.yml

      ## Test 1

      - name: "test: total coverage 0% (config)"
        uses: ./
        id: test-1
        with:
          version: ${{ inputs.version }}
          config: ./.github/workflows/testdata/zero.yml

      - name: "check: test output values"
        if: |
          steps.test-1.outputs.total-coverage == '' ||
          steps.test-1.outputs.badge-text == ''     ||
          steps.test-1.outputs.badge-color == ''    ||
          steps.test-1.outputs.report == ''
        run: echo "Previous step should have output values" && exit 1

      ## Test 2

      - name: "test: total coverage 100% (config)"
        uses: ./
        id: test-2
        continue-on-error: true
        with:
          version: ${{ inputs.version }}
          config: ./.github/workflows/testdata/total100.yml

      - name: "check: test should have failed"
        if: steps.test-2.outcome != 'failure'
        run: echo "Previous step should have failed" && exit 1

      - name: "check: test output values"
        if: |
          steps.test-2.outputs.total-coverage == '' ||
          steps.test-2.outputs.badge-text == ''     ||
          steps.test-2.outputs.badge-color == ''
        run: echo "Previous step should have output values" && exit 1

      ## Test 3

      - name: "test: total coverage 0% (inputs)"
        uses: ./
        id: test-3
        with:
          version: ${{ inputs.version }}
          profile: cover.out
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      ## Test 4

      - name: "test: total coverage 100% (inputs)"
        uses: ./
        id: test-4
        continue-on-error: true
        with:
          version: ${{ inputs.version }}
          profile: cover.out
          threshold-file: 0
          threshold-package: 0
          threshold-total: 100

      - name: "check: test should have failed"
        if: steps.test-4.outcome != 'failure'
        run: echo "Previous step should have failed" && exit 1

      ## Test 5

      - name: "test: override config"
        uses: ./
        id: test-5
        with:
          version: ${{ inputs.version }}
          config: ./.github/workflows/testdata/total100.yml
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      ## Test 6

      - name: "test: debug output"
        uses: ./
        id: test-6
        continue-on-error: true
        with:
          version: ${{ inputs.version }}
          profile: nonexistent-profile.out
          debug: true
          threshold-file: 0
          threshold-package: 0
          threshold-total: 100

      - name: "check: test should have failed"
        if: steps.test-6.outcome != 'failure'
        run: echo "Previous step should have failed" && exit 1
