name: integration-test
on: [push]
jobs:
  test:
    name: test
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set action image version to dev
        run: |
          yq e -i '.runs.image = "docker://ghcr.io/vladopajic/go-test-coverage:dev"' action.yml
          image=$(yq '.runs.image' action.yml)
          echo "Image: $image"

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            VERSION=dev
          tags: |
            ghcr.io/vladopajic/go-test-coverage:dev

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic

      - name: Test total coverage 0% (config)
        uses: ./
        with:
          config: ./.github/workflows/testdata/zero.yml

      - name: Test total coverage 100% (config)
        uses: ./
        id: should-fail-1
        continue-on-error: true
        with:
          config: ./.github/workflows/testdata/total100.yml
      
      - name: Check previous step failed
        if: steps.should-fail-1.outcome != 'failure'
        shell: bash
        run: |
          echo "Previous step should have failed"
          exit 1

      - name: Test total coverage 0% (inputs)
        uses: ./
        with:
          profile: cover.out
          local-prefix: "github.com/vladopajic/go-test-coverage"
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      - name: Test total coverage 100% (inputs)
        uses: ./
        id: should-fail-2
        continue-on-error: true
        with:
          profile: cover.out
          local-prefix: "github.com/vladopajic/go-test-coverage"
          threshold-file: 0
          threshold-package: 0
          threshold-total: 100
      
      - name: Check previous step failed
        if: steps.should-fail-2.outcome != 'failure'
        shell: bash
        run: |
          echo "Previous step should have failed"
          exit 1
